version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      # - ./client/package.json:/app/package.json
      # - ./client/package-lock.json:/app/package-lock.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
      
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]

#   mongo:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:
